version: "3.6"

services:
  indexer:
    image: ${SWARMLET_REGISTRY}/mempool:latest
    build:
        dockerfile: build/Dockerfile
        context: .
    depends_on:
      - db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - ADMIN_SECRET=${ADMIN_SECRET:-changeme}
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - mempool-network

  db:
    image: postgres:13
    restart: always
    volumes:
      - db:/var/lib/postgres/data
    environment: 
      - POSTGRES_USER=dipdup
      - POSTGRES_DB=dipdup
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - mempool-network

  hasura:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - 127.0.0.1:22000:8080
    depends_on:
      - db
    restart: always
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://dipdup:${POSTGRES_PASSWORD:-changeme}@db:5432/dipdup
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=true
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
      - HASURA_GRAPHQL_ADMIN_SECRET=${ADMIN_SECRET:-changeme}
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=user
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.mempool.loadbalancer.server.port=8080
        - traefik.http.routers.mempool.rule=Host(`mempool.${ROOT_DOMAIN}`)
        - traefik.http.routers.mempool.entrypoints=http,https,ws,wss
        - traefik.http.routers.mempool.middlewares=redirect@file
    networks:
      - mempool-network
      - traefik-public

  
volumes:
  db:

networks:
  mempool-network:
  traefik-public:
    external: true