{
 "title": "Mempool",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(go_goroutines, kubernetes_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(go_goroutines{kubernetes_namespace=\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(mempool_operation_count, network)"
    }
   },
   {
    "name": "interval",
    "query": "10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Mempool Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Operations By Kind",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kind) (rate(mempool_operation_count{job=\"mempool\",network=\"$network\"}[$interval]))*30",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Operations By Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(mempool_operation_count{job=\"mempool\",network=\"$network\"}[$interval]))*30",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Operations By Kind And Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kind, status) (rate(mempool_operation_count{job=\"mempool\",network=\"$network\"}[$interval]))*30",
     "legendFormat": "{{kind}}: {{status}}"
    }
   ]
  },
  {
   "title": "Operations Count By Kind And Status (series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (kind, status)(rate(mempool_operation_count{job=\"mempool\", network=\"$network\"}[$interval]))*30",
     "legendFormat": "{{kind}}: {{ status }}"
    }
   ]
  },
  {
   "title": "Transactions rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(mempool_operation_count{job=\"mempool\",network=\"$network\", kind=\"transaction\"}[$interval])*30",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Endorsements rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(mempool_operation_count{job=\"mempool\",network=\"$network\", kind=\"endorsement\"}[$interval])*30",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "RPC Errors By Node And Code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mempool_rpc_errors_count{job=\"mempool\",network=\"$network\"}[$interval])*30",
     "legendFormat": "{{node}} ({{code}})"
    }
   ]
  },
  {
   "title": "RPC Errors By Node And Code (series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "irate(mempool_rpc_errors_count{job=\"mempool\",network=\"$network\"}[$interval])*30",
     "legendFormat": "{{node}} ({{code}})"
    }
   ]
  }
 ]
}